/**
 * Rebuilds Text_deutsch_game/Story.txt from the Cutscene DSL source.
 *
 * Existing translations are retained by their English source key. Newly added
 * story lines are emitted with their English text as a visible fallback, ready
 * to translate on the second line as expected by Pokémon Essentials.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { localizeGermanSpeakerLabel, reviewedGermanStoryTranslations } from './story-translations-de';

const project = resolve(import.meta.dirname, '../../..');
const sourcePath = resolve(project, 'Data/Scripts/Story/Main_Story.rb');
const outputPath = resolve(project, 'Text_deutsch_game/Story.txt');

function unescapeRuby(value: string): string {
  return value.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
}

function existingTranslations(text: string, sourceKeys: Set<string>): Map<string, string> {
  const result = new Map<string, string>();
  const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/);
  const start = lines.findIndex((line) => line.trim() === '[SCRIPT_TEXTS]');
  for (let index = start + 1; index >= 1 && index + 1 < lines.length; index += 2) {
    const first = lines[index];
    const second = lines[index + 1];
    if (!first || first.startsWith('#')) continue;

    // Recover files whose key/translation lines were accidentally swapped.
    // The authoritative English keys always come from Main_Story.rb.
    if (sourceKeys.has(first)) result.set(first, second);
    else if (sourceKeys.has(second)) result.set(second, first);
  }
  return result;
}

const source = readFileSync(sourcePath, 'utf8');
const messages: string[] = [];
const seen = new Set<string>();
const pattern = /^\s*scene\.message\s+"((?:[^"\\]|\\.)*)"/gm;
for (const match of source.matchAll(pattern)) {
  const message = unescapeRuby(match[1]);
  if (!seen.has(message)) { seen.add(message); messages.push(message); }
}
const old = existsSync(outputPath)
  ? existingTranslations(readFileSync(outputPath, 'utf8'), seen)
  : new Map<string, string>();

const out = [
  '\uFEFF# Shattered Crowns story localization (English key, German translation)',
  '# Generated by: npm run extract:story',
  '# Translate every second line. Never change the English key above it.',
  '# Message controls such as \\b, \\PN, \\ts[] and placeholders must be preserved.',
  '#-------------------------------',
  '[SCRIPT_TEXTS]',
];
for (const message of messages) {
  const translation = reviewedGermanStoryTranslations.get(message) ?? old.get(message) ?? message;
  out.push(message, translation === message ? message : localizeGermanSpeakerLabel(translation));
}
writeFileSync(outputPath, `${out.join('\n')}\n`, 'utf8');
console.log(`Wrote ${messages.length} unique story messages to ${outputPath}`);
