import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const project = resolve(import.meta.dirname, '../../..');
const translations = [
  'Ein glasartiger schwarzer Stein, der beim Spalten eine scharfe Schneide bildet. Ein bestimmtes Pokémon liebt ihn.',
  'Ein Block aus schlammigem Material, der getrocknet als Brennstoff verwendet werden kann. Ein bestimmtes Pokémon liebt ihn.',
  'Ein sonderbarer Apfel, der die Entwicklung einer bestimmten Pokémon-Art auslöst. Er ist außergewöhnlich sirupreich.',
  'Eine sonderbare gesprungene Teetasse, die die Entwicklung einer bestimmten Pokémon-Art auslöst. Der Tee daraus schmeckt köstlich.',
  'Eine sonderbare angeschlagene Teetasse, die die Entwicklung einer bestimmten Pokémon-Art auslöst. Der Tee daraus schmeckt köstlich.',
  'Ein sonderbares Metall aus zahlreichen Schichten, das die Entwicklung einer bestimmten Pokémon-Art auslöst.',
  'Eine sonderbare Rüstung, die die Entwicklung einer bestimmten Pokémon-Art auslöst. In ihr lauert unheilvoller Wille.',
  'Eine sonderbare Rüstung, die die Entwicklung einer bestimmten Pokémon-Art auslöst. In ihr wohnen glückverheißende Wünsche.',
  'Eine kleine, seltene Bambussprosse, die bei einer bestimmten Art von Feinschmeckern sehr beliebt ist.',
  'Eine große, seltene Bambussprosse, die bei einer bestimmten Art von Feinschmeckern äußerst beliebt ist.',
  'Briefpapier mit dem Bild einer erfrischend grünen Wiese. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit dem Bild lodernder roter Flammen. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit dem Bild einer blauen Unterwasserwelt. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit hübschen Blumenmustern. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit dem Bild eines schwach beleuchteten Kohlebergwerks. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit coolen mechanischen Mustern. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit riesigen Herzmustern. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit dem Bild einer kalten, verschneiten Welt. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit dem Bild der unermesslichen Weite des Weltraums. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit einem Muster aus bunten Buchstaben. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit einem leuchtenden Regenbogenmuster. Gib es einem Pokémon zum Überbringen.',
  'Briefpapier mit einem robust wirkenden Ziegelmuster. Gib es einem Pokémon zum Überbringen.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte der KP eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte des Angriffs eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte der Verteidigung eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte des Spezial-Angriffs eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte der Spezial-Verteidigung eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er erhöht die Basispunkte der Initiative eines Pokémon.',
  'Ein Mochi, in dessen Teig Beeren eingearbeitet wurden. Er setzt sämtliche Basispunkte eines Pokémon zurück.',
  'Ein guter Hochleistungsball mit einer höheren Fangquote als ein gewöhnlicher Pokéball.',
  'Ein Ball zum Fangen wilder Pokémon. Er wird auf ein Pokémon geworfen und schließt das Ziel bequem in sich ein.',
  'Ein etwas ungewöhnlicher Pokéball, der umso effektiver ist, je schwerer das Pokémon ist.',
  'Dieser niedliche und ungewöhnliche Schild schützt den Träger davor, dass andere seine Fähigkeit verändern.',
  'Dieses klare, funkelnde Amulett verhindert, dass andere Pokémon die Statuswerte des Trägers senken.',
  'Dieser Kapuzenumhang verbirgt den Träger und schützt ihn vor Zusatzeffekten gegnerischer Attacken.',
  'Dieser gezinkte Würfel sorgt dafür, dass Serien-Attacken des Trägers häufiger treffen.',
  'Dieses Kraut spiegelt einmalig die Statuswerterhöhungen eines Gegners und erhöht dieselben Werte beim Träger.',
  'Die Energie in dieser Kapsel verstärkt Pokémon, die über bestimmte Fähigkeiten verfügen.',
  'Dieser Schutzhandschuh verstärkt Box-Attacken des Trägers und verhindert direkten Kontakt mit dem Ziel.',
  'Fügt der Träger einem Ziel mit einer Attacke Schaden zu, kann dieses zurückschrecken.',
  'Ein Item zum Tragen für Dialga. Der große, leuchtende Kristall steckt voller Kraft und ermöglicht ihm den Formwechsel.',
  'Ein Item zum Tragen für Palkia. Die große, leuchtende Kugel steckt voller Kraft und ermöglicht ihm den Formwechsel.',
  'Ein Item zum Tragen für Giratina. Der große, leuchtende Kristall steckt voller Kraft und ermöglicht ihm den Formwechsel.',
  'Eine geschnitzte Holzmaske für Ogerpon, durch die es im Kampf den Typ Wasser führen kann.',
  'Eine geschnitzte Holzmaske für Ogerpon, durch die es im Kampf den Typ Feuer führen kann.',
  'Eine geschnitzte Holzmaske für Ogerpon, durch die es im Kampf den Typ Gestein führen kann.',
  'Der Splitter einer offenbar uralten Klinge. Er wird nur von bestimmten Caesurio getragen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Heatran getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Darkrai getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Zygarde in seiner Optimumform getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Tectass getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Magearna getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Zeraora getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Nigiragi getragen, kann es eine Mega-Entwicklung durchführen.',
  'Einer von vielen rätselhaften Mega-Steinen. Wird er von Espinodon getragen, kann es eine Mega-Entwicklung durchführen.',
  'Eine sonderbare Schriftrolle mit den wahren Geheimnissen des Pfads der Finsternis. Sie löst bei einem bestimmten Pokémon die Entwicklung aus.',
  'Eine sonderbare Schriftrolle mit den wahren Geheimnissen des Pfads des Wassers. Sie löst bei einem bestimmten Pokémon die Entwicklung aus.',
  'Ein Ticket für das Schiff nach Berth Island. Es leuchtet wunderschön.',
  'Eine verblasste Seekarte, die den Weg zu einer bestimmten Insel weist.',
  'Eine Flöte aus schwarzem Glas. Ihr Klang verringert die Wahrscheinlichkeit, wilden Pokémon zu begegnen.',
  'Eine Flöte aus weißem Glas. Ihr Klang erhöht die Wahrscheinlichkeit, wilden Pokémon zu begegnen.',
  'Ein Wundspray, das die KP eines Pokémon um 50 auffüllt.',
  'Ein Wundspray, das die KP eines Pokémon um 200 auffüllt.',
  'Die berühmte Süßigkeit aus Mahagonia City. Sie füllt die KP eines Pokémon um 20 auf.',
  'Wasser mit hohem Mineralgehalt. Es füllt die KP eines Pokémon um 50 auf.',
  'Ein stark kohlensäurehaltiges Getränk. Es füllt die KP eines Pokémon um 60 auf.',
  'Ein sehr süßes und erfrischendes Getränk. Es füllt die KP eines Pokémon um 80 auf.',
  'Ein sehr bitteres Heilpulver. Es füllt die KP eines Pokémon um 50 auf.',
  'Eine sehr bittere Heilwurzel. Sie füllt die KP eines Pokémon um 200 auf.',
  'Erzeugt der Träger Hagel, hält dieser länger als gewöhnlich an.',
  'Eine wundersame Kugel zum Tragen für Latios oder Latias. Sie erhöht ihren Spezial-Angriff und ihre Spezial-Verteidigung.',
  'Ein Item, das im Kampf den Angriff eines Pokémon erhöht.',
  'Ein Item, das im Kampf die Verteidigung eines Pokémon erhöht.',
  'Ein Item, das im Kampf den Spezial-Angriff eines Pokémon erhöht.',
  'Ein Item, das im Kampf die Spezial-Verteidigung eines Pokémon erhöht.',
  'Ein Item, das im Kampf die Initiative eines Pokémon erhöht.',
  'Ein Item, das im Kampf die Genauigkeit eines Pokémon erhöht.',
] as const;

const path = resolve(project, 'Text_deutsch_core/ITEM_DESCRIPTIONS.txt');
const lines = readFileSync(path, 'utf8').replace(/^\uFEFF/, '').split(/\r?\n/);
const section = lines.indexOf('[ITEM_DESCRIPTIONS]');
const open: number[] = [];
for (let i = section + 1; i > 0 && i + 1 < lines.length; i += 2) if (lines[i] === lines[i + 1]) open.push(i + 1);
if (open.length !== translations.length) throw new Error(`Expected ${translations.length} open pairs, found ${open.length}`);
for (let i = 0; i < open.length; i++) lines[open[i]] = translations[i];
writeFileSync(path, `\uFEFF${lines.join('\n')}`, 'utf8');
console.log(`${translations.length} verbleibende Itembeschreibungen übersetzt.`);
