# Runs the Extra Map Layers plugin's real code against a fixture.
#
# The plugin's job — read Canopy and Sky out of an SCMap file and widen the
# map's tile Table to five layers — needs nothing from RGSS except `Table`, so
# it can be executed for real with a stub rather than only reviewed. Everything
# it produces is compared against expectations generated by the editor's own
# decoder, which is written independently, so agreement means something.
#
# What is still not covered: the renderer patch in [002], which needs a live
# TilemapRenderer, and therefore the game.
#
# Usage: ruby verify-extra-layers.rb <fixture-dir>

# --------------------------------------------------------------------- stubs

# RGSS's Table, in the shape the plugin uses it.
class Table
  attr_reader :xsize, :ysize, :zsize

  def initialize(xsize, ysize = 1, zsize = 1)
    @xsize = xsize
    @ysize = ysize
    @zsize = zsize
    @data = Array.new(xsize * ysize * zsize, 0)
  end

  def [](x, y = 0, z = 0)
    return @data[x + (y * @xsize) + (z * @xsize * @ysize)]
  end

  def []=(*args)
    value = args.pop
    x, y, z = args[0], args[1] || 0, args[2] || 0
    @data[x + (y * @xsize) + (z * @xsize * @ysize)] = value
  end
end

module EventHandlers
  def self.add(*_args); end
end

$log = []
def echoln(text)
  $log.push(text)
end

FakeMap = Struct.new(:width, :height, :data)

# ------------------------------------------------------------------ the plugin

PLUGIN = File.expand_path(
  "../../../Plugins/[SC] Extra Map Layers/[001] SCMap_ExtraLayers.rb", __dir__
)
abort("plugin not found at #{PLUGIN}") if !File.file?(PLUGIN)
load PLUGIN

# --------------------------------------------------------------------- fixture

fixture = ARGV[0]
abort("usage: ruby verify-extra-layers.rb <fixture-dir>") if !fixture

require "json"
expected = JSON.parse(File.read(File.join(fixture, "expected.json")))

# The plugin reads Data/SCMaps/MapNNN.json relative to the working directory.
Dir.chdir(fixture)

failures = []
checked = 0
canopy_total = 0
sky_total = 0

expected.each do |id_text, want|
  id = id_text.to_i
  width = want["width"]
  height = want["height"]

  # Seed the three layers RPG::Map would have carried.
  data = Table.new(width, height, 3)
  3.times do |z|
    flat = want["base"][z]
    height.times do |y|
      width.times { |x| data[x, y, z] = flat[(y * width) + x] }
    end
  end

  map = FakeMap.new(width, height, data)
  SCMapExtraLayers.apply(id, map)
  checked += 1

  if map.data.zsize != 5
    failures.push("map #{id}: zsize is #{map.data.zsize}, expected 5")
    next
  end

  # The original three layers must survive the widening untouched.
  mismatched_base = nil
  3.times do |z|
    flat = want["base"][z]
    height.times do |y|
      width.times do |x|
        got = map.data[x, y, z]
        expect = flat[(y * width) + x]
        mismatched_base ||= "layer #{z} at #{x},#{y}: got #{got}, expected #{expect}" if got != expect
      end
    end
  end
  failures.push("map #{id}: base #{mismatched_base}") if mismatched_base

  # And the two new ones must hold exactly what the editor draws.
  [["canopy", 3], ["sky", 4]].each do |name, z|
    flat = want[name]
    bad = nil
    count = 0
    height.times do |y|
      width.times do |x|
        got = map.data[x, y, z]
        expect = flat[(y * width) + x]
        count += 1 if expect != 0
        bad ||= "#{name} at #{x},#{y}: got #{got}, expected #{expect}" if got != expect
      end
    end
    canopy_total += count if name == "canopy"
    sky_total += count if name == "sky"
    failures.push("map #{id}: #{bad}") if bad
  end
end

puts
puts "Ruby plugin: #{checked - failures.length} of #{checked} fixtures widen to 5 layers correctly."
puts "  #{canopy_total} canopy and #{sky_total} sky tiles placed by the real plugin code."
skipped = $log.grep(/second tileset/)
puts "  #{skipped.length} map(s) reported tiles skipped for using a second tileset." if !skipped.empty?

if !failures.empty?
  puts
  puts "Failures:"
  failures.first(10).each { |line| puts "  #{line}" }
  puts "  ... and #{failures.length - 10} more" if failures.length > 10
end

exit(failures.empty? ? 0 : 1)
