#=============================================================================
# DRAGON Type Moves
#=============================================================================

GameData::Move.define :ROAROFTIME do |m|
  m.name "Roar of Time"
  m.type :DRAGON
  m.category :Special
  m.power 150
  m.accuracy 90
  m.pp 5
  m.target :NearOther
  m.function_code "AttackAndSkipNextTurn"
  m.description "The user blasts the target with power that distorts even time. The user must rest on the next turn."
end

GameData::Move.define :DRACOMETEOR do |m|
  m.name "Draco Meteor"
  m.type :DRAGON
  m.category :Special
  m.power 130
  m.accuracy 90
  m.pp 5
  m.target :NearOther
  m.function_code "LowerUserSpAtk2"
  m.description "Comets are summoned down from the sky. The attack's recoil harshly reduces the user's Sp. Atk stat."
end

GameData::Move.define :OUTRAGE do |m|
  m.name "Outrage"
  m.type :DRAGON
  m.category :Physical
  m.power 120
  m.accuracy 100
  m.pp 10
  m.target :RandomNearFoe
  m.function_code "MultiTurnAttackConfuseUserAtEnd"
  m.makes_contact
  m.description "The user rampages and attacks for two to three turns. It then becomes confused, however."
end

GameData::Move.define :DRAGONRUSH do |m|
  m.name "Dragon Rush"
  m.type :DRAGON
  m.category :Physical
  m.power 100
  m.accuracy 75
  m.pp 10
  m.target :NearOther
  m.function_code "FlinchTarget"
  m.effect_chance 20
  m.makes_contact
  m.description "The user tackles the foe while exhibiting overwhelming menace. It may also make the target flinch."
end

GameData::Move.define :SPACIALREND do |m|
  m.name "Spacial Rend"
  m.type :DRAGON
  m.category :Special
  m.power 100
  m.accuracy 95
  m.pp 5
  m.target :NearOther
  m.function_code "None"
  m.description "The user tears the target along with the space around it. Critical hits land more easily."
end

GameData::Move.define :DRAGONPULSE do |m|
  m.name "Dragon Pulse"
  m.type :DRAGON
  m.category :Special
  m.power 85
  m.accuracy 100
  m.pp 10
  m.target :Other
  m.function_code "None"
  m.description "The target is attacked with a shock wave generated by the user's gaping mouth."
end

GameData::Move.define :DRAGONCLAW do |m|
  m.name "Dragon Claw"
  m.type :DRAGON
  m.category :Physical
  m.power 80
  m.accuracy 100
  m.pp 15
  m.target :NearOther
  m.function_code "None"
  m.makes_contact
  m.description "The user slashes the target with huge, sharp claws."
end

GameData::Move.define :DRAGONTAIL do |m|
  m.name "Dragon Tail"
  m.type :DRAGON
  m.category :Physical
  m.power 60
  m.accuracy 90
  m.pp 10
  m.target :NearOther
  m.priority -6
  m.function_code "SwitchOutTargetDamagingMove"
  m.makes_contact
  m.description "The user knocks away the target and drags out another Pokémon in its party. In the wild, the battle ends."
end

GameData::Move.define :DRAGONBREATH do |m|
  m.name "Dragon Breath"
  m.type :DRAGON
  m.category :Special
  m.power 60
  m.accuracy 100
  m.pp 20
  m.target :NearOther
  m.function_code "ParalyzeTarget"
  m.effect_chance 30
  m.description "The user exhales a mighty gust that inflicts damage. It may also leave the target with paralysis."
end

GameData::Move.define :DUALCHOP do |m|
  m.name "Dual Chop"
  m.type :DRAGON
  m.category :Physical
  m.power 40
  m.accuracy 90
  m.pp 15
  m.target :NearOther
  m.function_code "HitTwoTimes"
  m.makes_contact
  m.description "The user attacks its target by hitting it with brutal strikes. The target is hit twice in a row."
end

GameData::Move.define :TWISTER do |m|
  m.name "Twister"
  m.type :DRAGON
  m.category :Special
  m.power 40
  m.accuracy 100
  m.pp 20
  m.target :AllNearFoes
  m.function_code "FlinchTargetDoublePowerIfTargetInSky"
  m.effect_chance 20
  m.description "The user whips up a vicious tornado to tear at the opposing team. It may also make targets flinch."
end

GameData::Move.define :DRAGONRAGE do |m|
  m.name "Dragon Rage"
  m.type :DRAGON
  m.category :Special
  m.power 1
  m.accuracy 100
  m.pp 10
  m.target :NearOther
  m.function_code "FixedDamage40"
  m.description "This attack hits the target with a shock wave of pure rage. This attack always inflicts 40 HP damage."
end

GameData::Move.define :DRAGONDANCE do |m|
  m.name "Dragon Dance"
  m.type :DRAGON
  m.category :Status
  m.accuracy 0
  m.pp 20
  m.target :User
  m.function_code "RaiseUserAtkSpd1"
  m.description "The user vigorously performs a mystic, powerful dance that boosts its Attack and Speed stats."
end

GameData::Move.define :CLANGINGSCALES do |m|
  m.name "Clanging Scales"
  m.type :DRAGON
  m.category :Special
  m.power 110
  m.accuracy 100
  m.pp 5
  m.target :AllNearFoes
  m.function_code "LowerUserDefense1"
  m.sound_based
  m.description "The user rubs its scales and makes a huge noise. Also lowers the user's Defense stat."
end

GameData::Move.define :COREENFORCER do |m|
  m.name "Core Enforcer"
  m.type :DRAGON
  m.category :Special
  m.power 100
  m.accuracy 100
  m.pp 10
  m.target :AllNearFoes
  m.function_code "NegateTargetAbilityIfTargetActed"
  m.description "If the target has already moved this turn, the effect of its Ability is negated."
end

GameData::Move.define :DRAGONHAMMER do |m|
  m.name "Dragon Hammer"
  m.type :DRAGON
  m.category :Physical
  m.power 90
  m.accuracy 100
  m.pp 15
  m.target :NearOther
  m.function_code "None"
  m.makes_contact
  m.description "The user uses its body like a hammer to attack the target and inflict damage."
end

GameData::Move.define :ETERNABEAM do |m|
  m.name "Eternabeam"
  m.type :DRAGON
  m.category :Special
  m.power 160
  m.accuracy 90
  m.pp 5
  m.target :NearOther
  m.function_code "AttackAndSkipNextTurn"
  m.description "This is Eternatus's most powerful attack in its original form. The user can't move on the next turn."
end

GameData::Move.define :DRAGONENERGY do |m|
  m.name "Dragon Energy"
  m.type :DRAGON
  m.category :Special
  m.power 150
  m.accuracy 100
  m.pp 5
  m.target :AllNearFoes
  m.function_code "PowerHigherWithUserHP"
  m.description "Converts life-force into power to attack. The lower the user's HP, the lower the move's power."
end

GameData::Move.define :DYNAMAXCANNON do |m|
  m.name "Dynamax Cannon"
  m.type :DRAGON
  m.category :Special
  m.power 100
  m.accuracy 100
  m.pp 5
  m.target :NearOther
  m.function_code "DoubleDamageOnDynamaxTargets"
  m.description "The user unleashes a strong beam from its core."
end

GameData::Move.define :BREAKINGSWIPE do |m|
  m.name "Breaking Swipe"
  m.type :DRAGON
  m.category :Physical
  m.power 60
  m.accuracy 100
  m.pp 15
  m.target :AllNearFoes
  m.function_code "LowerTargetAttack1"
  m.effect_chance 100
  m.makes_contact
  m.description "The user swings its tough tail wildly and attacks all foes. This also lowers their Attack stats."
end

GameData::Move.define :DRAGONDARTS do |m|
  m.name "Dragon Darts"
  m.type :DRAGON
  m.category :Physical
  m.power 50
  m.accuracy 100
  m.pp 10
  m.target :NearOther
  m.function_code "HitTwoTimesTargetThenTargetAlly"
  m.description "The user attacks twice using Dreepy. If there are two targets, this move hits each one once."
end

GameData::Move.define :SCALESHOT do |m|
  m.name "Scale Shot"
  m.type :DRAGON
  m.category :Physical
  m.power 25
  m.accuracy 90
  m.pp 20
  m.target :NearOther
  m.function_code "HitTwoToFiveTimesRaiseUserSpd1LowerUserDef1"
  m.description "Attacks by shooting scales two to five times in a row. Boosts the user's Speed but lowers its Defense."
end

GameData::Move.define :CLANGOROUSSOUL do |m|
  m.name "Clangorous Soul"
  m.type :DRAGON
  m.category :Status
  m.accuracy 0
  m.pp 5
  m.target :User
  m.function_code "RaiseUserMainStats1LoseThirdOfTotalHP"
  m.description "The user raises all its stats by using some of its HP."
end

GameData::Move.define :GLAIVERUSH do |m|
  m.name "Glaive Rush"
  m.type :DRAGON
  m.category :Physical
  m.power 120
  m.accuracy 100
  m.pp 5
  m.target :NearOther
  m.function_code "UserVulnerableUntilNextAction"
  m.makes_contact
  m.description "The user becomes highly vulnerable to attacks until its next turn after using this move."
end

GameData::Move.define :ORDERUP do |m|
  m.name "Order Up"
  m.type :DRAGON
  m.category :Physical
  m.power 80
  m.accuracy 100
  m.pp 10
  m.target :NearOther
  m.function_code "RaiseUserStat1Commander"
  m.effect_chance 100
  m.description "If used when the user has a Tatsugiri in its mouth, a boost occurs based on its form."
end

GameData::Move.define :FICKLEBEAM do |m|
  m.name "Fickle Beam"
  m.type :DRAGON
  m.category :Special
  m.power 80
  m.accuracy 100
  m.pp 5
  m.target :NearOther
  m.function_code "RandomlyDealsDoubleDamage"
  m.description "Sometimes all of the user's heads shoot beams in unison, doubling this move's power."
end

GameData::Move.define :DRAGONCHEER do |m|
  m.name "Dragon Cheer"
  m.type :DRAGON
  m.category :Status
  m.accuracy 0
  m.pp 15
  m.target :AllAllies
  m.function_code "RaiseAlliesCriticalHitRate1DragonTypes2"
  m.description "The user raises its allies’ critical hit ratio with a draconic cry. This rouses Dragon types more."
end

GameData::Move.define :NIHILLIGHT do |m|
  m.name "Nihil Light"
  m.type :DRAGON
  m.category :Special
  m.power 200
  m.accuracy 100
  m.pp 10
  m.target :AllNearFoes
  m.function_code "IgnoreTargetDefSpDefEvaStatStagesHitFairyType"
  m.description "A powerful light that defies nature, striking Fairy types and ignoring target stat changes."
end
